import type { Metadata } from "next";
import { Noto_Serif_Bengali, Roboto } from "next/font/google";
import "./globals.css";
import ProvidersWrapper from "@/components/Providers/ProvidersWrapper";
import { Toaster } from "sonner";

const notoSerifBengali = Noto_Serif_Bengali({
  weight: ['400', '500', '600', '700'],
  subsets: ["bengali"],
  variable: "--font-noto-serif-bengali",
  display: 'swap',
});

const roboto = Roboto({
  weight: ['400', '500', '700'],
  subsets: ["latin"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Hello Shop!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${notoSerifBengali.variable} ${roboto.variable} font-roboto`}>
        <ProvidersWrapper>
          {children}
        </ProvidersWrapper>
      </body>
    </html>
  );
}
